openapi: 3.0.1
info:
  title: Questforge Chronicles
  description: 'Contract for Questforge-Chronicles service.'
  version: 1.0.0
servers:
  - url: http://localhost/v1
tags:
  - name: Adventurer
    description: Adventurer related
  - name: Quest
    description: Quest related
paths:
  /adventurer/{id}:
    get:
      tags:
        - Adventurer
      summary: Get a Adventurer with ID
      description: Returns a Adventurer
      operationId: getAdventurerById
      parameters:
        - name: id
          in: path
          description: ID of the Adventurer
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Adventurer'
        400:
          description: Invalid parameters are supplied
          content: {}
  /quest/{id}:
    get:
      tags:
        - Quest
      summary: Get a Quest with ID
      description: Returns a Quest
      operationId: getQuestById
      parameters:
        - name: id
          in: path
          description: ID of the Quest
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quest'
        400:
          description: Invalid parameters are supplied
          content: {}
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BasicErrorModel'
  schemas:
    Adventurer:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Adventurer Id
        name:
          type: string
          description: Adventurer name
        background:
          type: string
          description: What need to know about this Adventurer
        quests:
          type: array
          items:
            $ref: '#/components/schemas/Quest'
      example:
        id: 97
        name: "Salazar"
        description: "A pirate from the moon."
    
    Quest:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Quest Id
        name:
          type: string
          description: Quest name
        description:
          type: string
          description: What need to know about this Quest
      example:
        id: 97
        name: "Bring it on"
        description: "Never stop."

    BasicErrorModel:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
          
    ExtendedErrorModel:
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: '#/components/schemas/BasicErrorModel'
        - type: object
          required:
            - rootCause
          properties:
            rootCause:
              type: string